In [2]:
import pickle

import numpy as np

In [2]:
pickle_file = 'data/sensor_graph/adj_mx.pkl'
with open(pickle_file, 'rb') as f:
    pickle_data = pickle.load(f, encoding='latin1')

In [3]:
sensor_ids, sensor_id_to_ind, adj_mx = pickle_data

In [4]:
adj_mx

array([[1.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 1.       , 0.3909554, ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.7174379, 1.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.       , 0.       , ..., 1.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 1.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        1.       ]], dtype=float32)

In [5]:
with open(r'E:\develop\gnn_cargo\embedding\id_label_set.pkl', 'rb') as f:
    id_label_set = pickle.load(f)
    

In [6]:
adj_mx = np.zeros((len(id_label_set), len(id_label_set)))

In [7]:
id_label_set

{'0_0': 4,
 '0_1': 1,
 '0_2': 4,
 '0_3': 6,
 '0_4': 0,
 '0_5': 4,
 '0_6': 4,
 '0_7': 4,
 '0_8': 4,
 '0_9': 4,
 '0_10': 4,
 '0_11': 4,
 '0_12': 1,
 '0_13': 4,
 '0_14': 1,
 '0_15': 4,
 '0_16': 1,
 '0_17': 4,
 '0_18': 1,
 '0_19': 1,
 '0_20': 6,
 '0_21': 0,
 '0_22': 0,
 '0_23': 7,
 '0_24': 7,
 '0_25': 2,
 '0_26': 8,
 '0_27': 0,
 '0_28': 6,
 '0_29': 1,
 '1_0': 6,
 '1_1': 6,
 '1_2': 6,
 '1_3': 8,
 '1_4': 0,
 '1_5': 4,
 '1_6': 1,
 '1_7': 1,
 '1_8': 1,
 '1_9': 1,
 '1_10': 1,
 '1_11': 1,
 '1_12': 4,
 '1_13': 4,
 '1_14': 4,
 '1_15': 1,
 '1_16': 1,
 '1_17': 1,
 '1_18': 1,
 '1_19': 1,
 '1_20': 6,
 '1_21': 7,
 '1_22': 8,
 '1_23': 7,
 '1_24': 5,
 '1_25': 2,
 '1_26': 8,
 '1_27': 8,
 '1_28': 0,
 '1_29': 6,
 '2_0': 1,
 '2_1': 6,
 '2_2': 8,
 '2_3': 3,
 '2_4': 6,
 '2_5': 1,
 '2_6': 1,
 '2_7': 4,
 '2_8': 1,
 '2_9': 1,
 '2_10': 1,
 '2_11': 1,
 '2_12': 1,
 '2_13': 4,
 '2_14': 4,
 '2_15': 4,
 '2_16': 4,
 '2_17': 1,
 '2_18': 1,
 '2_19': 6,
 '2_20': 1,
 '2_21': 3,
 '2_22': 3,
 '2_23': 3,
 '2_24': 3,
 '2_25': 7

In [8]:
#id_label_set转list
id_list = []
label_list = []
for i in id_label_set:
    id_list.append(i)
    label_list.append(id_label_set[i])
    

In [28]:
for i in range(len(id_list)):
    for j in range(len(id_list)):
        if label_list[i] == label_list[j]:
            adj_mx[i][j] = 1

In [29]:
adj_mx

array([[1., 0., 1., ..., 1., 1., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 1., 1., 1.],
       ...,
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.]])

In [32]:
for i in range(len(id_list)):
    for j in range(len(id_list)):
        row1,col1 = id_list[i].split('_')
        row2,col2 = id_list[j].split('_')
        #判断是否相邻
        if abs(int(row1)-int(row2)) == 1 and abs(int(col1)-int(col2)) == 0:
            adj_mx[i][j] = 1
        elif abs(int(row1)-int(row2)) == 0 and abs(int(col1)-int(col2)) == 1:
            adj_mx[i][j] = 1
            
        


In [33]:
adj_mx

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.]])

In [35]:
#保存
with open(r'E:\develop\gnn_cargo\embedding\adj_mx_test.pkl', 'wb') as f:
    pickle.dump(adj_mx, f, pickle.HIGHEST_PROTOCOL)

In [3]:
#读取
with open(r'E:\develop\gnn_cargo\embedding\adj_mx_test.pkl', 'rb') as f:
    adj_mx = pickle.load(f)

In [4]:
adj_mx

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.]])